employee/urls.py
from django.urls import include,path
from . import views
urlpatterns = [
        
    path('',views.homepage),
    path('admin-dashboard', views.admindashboard),
    path('employee-dashboard',views.employeedashboard),
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:eid>', views.edit),  
    path('update/<int:eid>', views.update),  
    path('delete/<int:eid>', views.destroy),
    path('verify_employee/<int:id>',views.verify_employee)
]

tmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
# from tsystem import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('employee.urls')),
    path('',include('vehicle.urls')),
    path('',include('user.urls')),
    path('',include('travel.urls'))
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import include,path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('register/', views.register, name="register"),
    path('profile/', views.profile, name="profile"),
    path('logout/', views.logoutUser),
    path('add_user_details',views.add_user_detail),
    path('edit_user_details',views.edit_user_details),
    path('update_user_details',views.update_user_details)
]

employee/models.py
from django.db import models

class Employee(models.Model):  

    eid = models.AutoField(primary_key=True)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)
    edob = models.DateField(default='2000-01-01')
    eaddhar = models.CharField(max_length=14 , default="Not Mentioned")
    isverified = models.BooleanField(default=False)
    # eimage = models.ImageField(upload_to='images/' , default="Not Provided")

    class Meta:  
        db_table = "employee" 

employee/forms.py
from django import forms  
from .models import Employee
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__" 

employee/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import EmployeeForm 
from .models import Employee
from .decorators import *
from datetime import date
from django.contrib.auth.decorators import login_required
#Load home page
def homepage(request):
    return render(request,'home_page.html')


# Create your views here.  
def emp(request):  
    employee=Employee.objects.last()
    if employee==None:
        eid = 1
    else:
        eid = employee.eid + 1
    if request.method == "POST":  
        form = EmployeeForm(request.POST,request.FILES)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:
                pass
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form , 'id':eid}) 

@login_required(login_url='/login')
@allowed_users(['admin'])
def show(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})


@login_required(login_url='/login')
@allowed_users(['employee','admin'])  
def edit(request, eid):
    employee = Employee.objects.get(eid=eid)  
    fdob = str(employee.edob)
    return render(request,'edit.html', {'employee':employee , 'fdob':fdob}) 

@login_required(login_url='/login')
@allowed_users(['employee','admin']) 
def update(request, eid):  
    employee = Employee.objects.get(eid=eid)
    employee.isverified = False  
    form = EmployeeForm(request.POST, instance = employee)  
    print(form.errors)
    if form.is_valid():  
        form.save()  
        return redirect("/show") 
    fdob = str(employee.edob)
    return render(request, 'edit.html', {'employee': employee , 'fdob' : fdob})

@login_required(login_url='/login')
@allowed_users(['admin'])
def destroy(request, eid):  
    employee = Employee.objects.get(eid=eid)  
    employee.delete()  
    return redirect("/show")

@login_required(login_url='/login')
@allowed_users(['admin'])
def admindashboard(request):
    return render(request,'admin_dashboard.html')

@login_required
@allowed_users(['admin'])
def verify_employee(request , id):
    employee = Employee.objects.get(eid = id)
    employee.isverified = True
    employee.save()
    return render(request,'message.html', {'error':False, 'message':'Verified ' + employee.ename+' Successfully' , 'links':[{'olink':'show' , 'text':"Click"}]})

@login_required(login_url='/login')
@allowed_users(['admin','employee'])
def employeedashboard(request):
    return render(request,'employee_dashboard.html')

employee/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
    <style>
         @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&family=Poppins:wght@400;500;600&display=swap');
      body{
        background-image: url('../static/images/beach.jpg');
        background-repeat: no-repeat;
        background-size:cover ;
        font-family:  'Poppins', sans-serif;
      }
    </style>
  </head>
  <body>
      <h1 style="color: aliceblue; display: flex; justify-content: center; text-decoration: underline;">Admin Dash Board</h1>
      <center>
        <div style="display: flex; color: black; justify-content: space-evenly; flex-direction: row; align-items: center; height: 40vh; width: 60vw; flex-wrap: wrap;">
          <a class="m-10 btn btn-success btn-lg" href="/emp">Add Employee</a>
          <a class="m-10 btn btn-success btn-lg" href="/vehicle_add">Add Vehicle</a>
          <a class="m-10 btn btn-success btn-lg" href="/vehicle_get">Show Vehicles</a>
          <a class="m-10 btn btn-success btn-lg" href="/add_location">Add new add_location</a>
          <a class="m-10 btn btn-success btn-lg" href="/show">Show employee Details</a>
          <a class="m-10 btn btn-success btn-lg" href="/admin/travel/booktrip/">Show Trip Details</a>
          <a type="button" class="m-10 btn btn-danger" href="/logout">Logout</a>
        </div>
      </center>
      

  </body>
</html>

employee/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <style>
      .form_div {
      display: flex;
      flex-direction: column;
    }
    .form_div div {
      margin: 1rem;
    }
    * {
      padding: 0;
      margin: 0;
      box-sizing: border-box;
      font-family: 'Quicksand', sans-serif;
    }

    body {
      height: 100vh;
      width: 100%;
    }

    .container {
      position: relative;
      width: 100%;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 20px 100px;
    }

    .container:after {
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      left: 0;
      top: 0;
      background: url('../static/images/bg.jpg') no-repeat center;
      background-size: cover;
      filter: blur(50px);
      z-index: -1;
    }
    .contact-box {
      max-width: 850px;
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      justify-content: center;
      align-items: center;
      text-align: center;
      background-color: #fff;
      box-shadow: 0px 0px 19px 5px rgba(0, 0, 0, 0.19);
    }

    .left {
      background: url('../static/images/bg.jpg') no-repeat center;
      background-size: cover;
      height: 100%;
    }

    .right {
      padding: 25px 40px;
    }

    h2 {
      position: relative;
      padding: 0 0 10px;
      margin-bottom: 10px;
    }

    h2:after {
      content: '';
      position: absolute;
      left: 50%;
      bottom: 0;
      transform: translateX(-50%);
      height: 4px;
      width: 50px;
      border-radius: 2px;
      background-color: #2691d9;
    }

    .field {
      width: 100%;
      border: 2px solid rgba(0, 0, 0, 0);
      outline: none;
      background-color: rgba(230, 230, 230, 0.6);
      padding: 0.5rem 1rem;
      font-size: 1.1rem;
      margin-bottom: 22px;
      transition: 0.3s;
    }

    .field:hover {
      background-color: rgba(0, 0, 0, 0.1);
    }

    textarea {
      min-height: 150px;
    }

    .btn {
      width: 100%;
      padding: 0.5rem 1rem;
      background-color: #2691d9;
      color: #fff;
      font-size: 1.1rem;
      border: none;
      outline: none;
      cursor: pointer;
      transition: 0.3s;
    }

    .btn:hover {
      background-color: #2691d9;
    }

    .field:focus {
      border: 2px solid rgba(30, 85, 250, 0.47);
      background-color: #fff;
    }

    @media screen and (max-width: 880px) {
      .contact-box {
        grid-template-columns: 1fr;
      }
      .left {
        height: 200px;
      }
    }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="contact-box">
        <div class="left"></div>
        <div class="right">
          <h2>Employee Details</h2>
          <form method="post" action="/update/{{employee.eid}}">
            {% csrf_token %}
            <input type="number" name="eid" class="field" value="{{ employee.eid }}"/>
            <input
              required
              type="text"
              name="ename"
              class="field"
              placeholder="Employee Name"
              value="{{ employee.ename }}"
            />
            <input
              required
              type="email"
              class="field"
              name="eemail"
              placeholder="Employee Email"
              value="{{ employee.eemail }}"
            />
            <input
              required
              type="text"
              class="field"
              name="econtact"
              value="{{ employee.econtact }}"
              placeholder="Phone Number"
            />
            <input
              type="date"
              name="edob"
              class="field"
              value="{{fdob}}"
              placeholder="dd/mm/yyyy"
            />
            <input
              type="text"
              name="eaddhar"
              class="field"
              placeholder="Employee Addhar"
              value="{{ employee.eaddhar }}"
            />
            <input type="submit" class="btn" />
          </form>
        </div>
      </div>
    </div>
    <!-- <form method="POST" class="post-form" action="/update/{{employee.eid}}">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Update Details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Id:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="eid"
              id="id_eid"
              required
              maxlength="20"
              value="{{ employee.eid }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Name:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="ename"
              id="id_ename"
              required
              maxlength="100"
              value="{{ employee.ename }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Email:</label>
          <div class="col-sm-4">
            <input
              type="email"
              name="eemail"
              id="id_eemail"
              required
              maxlength="254"
              value="{{ employee.eemail }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Contact:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="econtact"
              id="id_econtact"
              required
              maxlength="15"
              value="{{ employee.econtact }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Age:</label>
          <div class="col-sm-4">
            <input
              id = 'getdate'
              type="date"
              name="edob"
              value="{{fdob}}"
            />
           <input
              type="number"
              name="eage"
              id="id_econtact"
              required
              min="18"
              max="50"
              value="{{ employee.eage }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Addhar Number:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="eaddhar"
              id="id_econtact"
              required
              value="{{ employee.eaddhar }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <div>{{form.errors}}</div>
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
        </div>
      </div>
    </form> -->
    <script>
      var getdob = document.getElementById('getdate');
      console.log(getdob.value);
    </script>
  </body>
</html>

employee/templates/employee_dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>This is Employee DashBoard</h1>
    <a href="/logout">Click here to Logout!</a>
  </body>
</html>

employee/templates/home_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
    <title>Document</title>
    {% load static %}
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&family=Poppins:wght@400;500;600&display=swap');
    body {
      background: url('../static/images/car1.jpeg') no-repeat;
      background-size: cover;
    }
    .box {
      color: white;
      font-family: 'Poppins', sans-serif;
    }
    a {
      color: white;
      text-decoration: none;
    }
    a:hover {
      color: white;
      text-decoration: none;
    }
    .btns {
      display: flex;
      width: 40vw;
      justify-content: space-between;
      margin: 200px;
    }
  </style>
  <body>
    <div class="box">
      <center><h1 style="margin: 10vh">Welcome {{request.user}}!</h1></center>
      <center>
        <div class="btns">
          <a class="btn btn-primary btn-lg" href="/travel_book">Book a trip</a>
          <a class="btn btn-success btn-lg" href="/profile">Profile</a>
        </div>
      </center>
    </div>
  </body>
</html>

employee/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
  </head>
  <style>
    .form_div {
      display: flex;
      flex-direction: column;
    }
    .form_div div {
      margin: 1rem;
    }
    * {
      padding: 0;
      margin: 0;
      box-sizing: border-box;
      font-family: 'Quicksand', sans-serif;
    }

    body {
      height: 100vh;
      width: 100%;
    }

    .container {
      position: relative;
      width: 100%;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 20px 100px;
    }

    .container:after {
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      left: 0;
      top: 0;
      background: url('../static/images/bg.jpg') no-repeat center;
      background-size: cover;
      filter: blur(50px);
      z-index: -1;
    }
    .contact-box {
      max-width: 850px;
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      justify-content: center;
      align-items: center;
      text-align: center;
      background-color: #fff;
      box-shadow: 0px 0px 19px 5px rgba(0, 0, 0, 0.19);
    }

    .left {
      background: url('../static/images/bg.jpg') no-repeat center;
      background-size: cover;
      height: 100%;
    }

    .right {
      padding: 25px 40px;
    }

    h2 {
      position: relative;
      padding: 0 0 10px;
      margin-bottom: 10px;
    }

    h2:after {
      content: '';
      position: absolute;
      left: 50%;
      bottom: 0;
      transform: translateX(-50%);
      height: 4px;
      width: 50px;
      border-radius: 2px;
      background-color: #2691d9;
    }

    .field {
      width: 100%;
      border: 2px solid rgba(0, 0, 0, 0);
      outline: none;
      background-color: rgba(230, 230, 230, 0.6);
      padding: 0.5rem 1rem;
      font-size: 1.1rem;
      margin-bottom: 22px;
      transition: 0.3s;
    }

    .field:hover {
      background-color: rgba(0, 0, 0, 0.1);
    }

    textarea {
      min-height: 150px;
    }

    .btn {
      width: 100%;
      padding: 0.5rem 1rem;
      background-color: #2691d9;
      color: #fff;
      font-size: 1.1rem;
      border: none;
      outline: none;
      cursor: pointer;
      transition: 0.3s;
    }

    .btn:hover {
      background-color: #2691d9;
    }

    .field:focus {
      border: 2px solid rgba(30, 85, 250, 0.47);
      background-color: #fff;
    }

    @media screen and (max-width: 880px) {
      .contact-box {
        grid-template-columns: 1fr;
      }
      .left {
        height: 200px;
      }
    }
  </style>
  <body>
    <div class="container">
      <div class="contact-box">
        <div class="left"></div>
        <div class="right">
          <h2>Employee Details</h2>
          <form action="" method="post">
            {% csrf_token %}
            <input type="number" name="eid" class="field" value="{{id}}" />
            <input
              required
              type="text"
              name="ename"
              class="field"
              placeholder="Employee Name"
            />
            <input
              required
              type="email"
              class="field"
              name="eemail"
              placeholder="Employee Email"
            />
            <input
              required
              type="text"
              class="field"
              name="econtact"
              placeholder="Phone Number"
            />
            <input
              type="date"
              name="edob"
              class="field"
              placeholder="dd/mm/yyyy"
            />
            <input
              type="text"
              name="eaddhar"
              class="field"
              placeholder="Employee Addhar"
            />
            <input type="submit" class="btn" />
          </form>
        </div>
      </div>
    </div>
    <!-- <form
      method="POST"
      class="post-form"
      action="/emp"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Enter Details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Id:</label>
          <div class="col-sm-4">
            <input type="text" value="{{id}}" disabled />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Name:</label>
          <div class="col-sm-4">{{ form.ename }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Email:</label>
          <div class="col-sm-4">{{ form.eemail }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Contact:</label>
          <div class="col-sm-4">{{ form.econtact }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee DOB:</label>
          <div class="col-sm-4">
            <input type="date" id="mydate" name="edob" />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Addhar Number:</label>
          <div class="col-sm-4">{{ form.eaddhar }}</div>
        </div>
        <div>{{form.errors}}</div><div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Picture:</label>
          <div class="col-sm-4">{{ form.eimage }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>
    </form> -->
    <script>
      let date = new Date();
      let day = date.getDate();
      let month = date.getMonth() + 1;
      let year = date.getFullYear();
      const current = `${year}-${month % 10 == 0 ? '' : '0'}${month}-${day}`;
      console.log(current);
      my_date = document.getElementById('mydate');
      my_date.max = current;
    </script>
  </body>
</html>

employee/templates/message.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <style>
    * {
      margin: 0;
      padding: 0;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI',
        Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue',
        sans-serif;
    }
    .center {
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .box {
      width: 30vw;
      height: 20vh;
      border-radius: 2rem;
      border: 2px solid black;
      display: flex;
      align-items: center;
      justify-content: space-between;
      flex-direction: column;
    }
    .links {
      display: flex;
      flex-direction: column;
    }
    .msg_head {
      margin-top: 1rem;
      width: 100%;
      display: flex;
      justify-content: center;
    }
    .links {
      display: flex;
      width: 100%;
      flex-direction: row;
      align-items: center;
      justify-content: space-evenly;
      padding: 1rem;
    }
    .links a {
      background-color: aliceblue;
      padding: 0.5rem;
      border-radius: 0.6rem;
      text-decoration: none;
      color: black;
      font-weight: 700;
    }
  </style>
  <body>
    <div class="center">
      <div class="box">
        <h2 class="msg_head">{{message}}</h2>
        <div class="links">
          {% for link in links %}
          <a href="/{{link.olink}}">{{link.text}}</a>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>

employee/templates/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Employee Records</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
    {% load static %}
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&family=Poppins:wght@400;500;600&display=swap');
    * {
      margin: 0;
      padding: 0;
      font-family: 'Poppins', sans-serif;
    }
    .th {
      margin-right: 300px;
    }
    td p {
      color: blue;
    }
    .ver {
      color: green;
    }
    th p {
      margin-right: 2rem;
    }
  </style>
  <body>
    <div class="container" style="margin-top: 10vh">
      <div style="overflow-x: scroll" class="row">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Employee Id</th>
              <th>Employee Name</th>
              <th>Employee Email</th>
              <th>Employee Contact</th>
              <th>Employee DOB</th>
              <th>Employee Addhar</th>
              <th>Verified</th>
              <th>Actions</th>
              <!-- <th>Edit</th> -->
            </tr>
          </thead>
          <tbody>
            {% for employee in employees %}
            <tr>
              <td><p>{{ employee.eid }}</p></td>
              <td>{{ employee.ename }}</td>
              <td>{{ employee.eemail }}</td>
              <td>{{ employee.econtact }}</td>
              <td>{{employee.edob}}</td>
              <td>{{employee.eaddhar}}</td>
              <td>
                <!-- {{ employee.isverified }} -->
                {% if employee.isverified %}
                <p class="ver">Verified</p>
                {% else %}
                <p>Not Verified</p>
                {% endif %}
              </td>
              <!-- <img
                width="50px"
                height="50px"
                src="../../../media/{{employee.eimage}}"
                alt="Not provided"
              /> -->

              <td>
                <a
                  class="btn btn-warning"
                  style="margin-right: 1rem"
                  href="/edit/{{ employee.eid }}"
                  ><span class="glyphicon glyphicon-pencil">Edit</span></a
                >
                <a class="btn btn-danger" href="/delete/{{ employee.eid }}"
                  >Delete</a
                >
                {% if not employee.isverified %}
                <a
                  class="btn btn-secondary"
                  href="/verify_employee/{{employee.eid}}"
                  >Verify</a
                >
                >{% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
  </body>
</html>